### ISSUE TITLE
How can I cope with lists of IP addresses?

### ISSUE THREAD

**Issue by andrewrutter** [varnish/libvmod-geoip#10]
I have varnish running on a website that is sitting behind Amazon Cloudfront. This is appending a rogue IP address to X-Forwarded-For so geoip.country_code(req.http.X-Forwarded-For); is failing to locate and just returning undefined

How can I handle this list of IP Addresses, I know that the first one in the list is the users original one. I have tried to fnd a way to stop this behavior in Cloudfront but it seems to be baked in. I have also tried to bypass for the main page request but that impacts how many objects end up in cache due to relative URL's

Thanks!

**Comment by gquintard** [comment]
you'll need to use regsub() to isolate the ip you are interested in.
