### ISSUE TITLE
Does this module support IPv6?

### ISSUE THREAD

**Issue by Rod-Gomes** [varnish/libvmod-geoip#15]
I'm trying to get the country code from an Ipv6 and returns **unknown**.

**Comment by gquintard** [comment]
Let's try to use the help channels (http://varnish-cache.org/support/index.html#) before opening bug tickets.

If you don't have an IPv6 database, the result is expected. If you do, please reach out via one of the help channels.

**Comment by Rod-Gomes** [comment]
@gquintard Well, let's try again:

I have the default GeoIP databases installed.
```
[~]# ls /usr/share/GeoIP
./   GeoIP.dat@      GeoIP-initial.dat  GeoIPv6-initial.dat
../  GeoIP.dat.test  GeoIPv6.dat@ 
[~]# yum list installed | grep -i geoip
GeoIP.x86_64                               1.5.0-11.el7                @base    
GeoIP-devel.x86_64                         1.5.0-11.el7                @cloudlinux-x86_64-server-7
GeoIP-update.noarch                        1.5.0-11.el7                @cloudlinux-x86_64-server-7
```

`geoiplookup6` Lookup IPv6 normally:
```
[~]# geoiplookup6 2804:14c:87c1:8a3d::1005
GeoIP Country V6 Edition: BR, Brazil
```

But, `geoip.country_code(client.ip)` does not lookup the same IPv6 above.

Is there any special configuration for lookup the country with IPv6?
