### ISSUE TITLE
Support for .mmdb GeoIP database

### ISSUE THREAD

**Issue by csandanov** [varnish/libvmod-geoip#18]
Since January 2, 2019 MaxMind [no longer supports](https://support.maxmind.com/geolite-legacy-discontinuation-notice/) legacy `.dat` database but they still have a free geolite `.mmdb` database. It would be great if this module support it. As for example there's a VCL script in Alpine's varnish package repository that works with `mmdb`: https://git.alpinelinux.org/aports/tree/main/varnish/maxminddb.vcl?h=3.8-stable

**Comment by gquintard** [comment]
Hi,

so it took us so long to reply. As you mentioned, `libgeoip` is now obsolete, so this vmod is too. Any effort toward this will occur outside of this repo.

Note that Varnish Plus already has [vmod_mmdb](https://docs.varnish-software.com/varnish-cache-plus/vmods/geolocation/)
