### ISSUE TITLE
Error when install libvmod 1.0.2

### ISSUE THREAD

**Issue by nnhiep** [varnish/libvmod-geoip#5]
Hi Team 

I install libvmod-geoip + varnish 4 on centos 7 --> error when run make command

vmod_geoip.c:21:48: error: 'enum vcl_event_e' declared inside parameter list [-Werror]
 vmod_event(VRT_CTX, struct vmod_priv *pp, enum vcl_event_e evt)
                                                ^
vmod_geoip.c:21:48: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
vmod_geoip.c:21:60: error: parameter 3 ('evt') has incomplete type
 vmod_event(VRT_CTX, struct vmod_priv *pp, enum vcl_event_e evt)
                                                            ^
In file included from /usr/include/varnish/common/common.h:37:0,
                 from /usr/include/varnish/cache/cache.h:37,
                 from vmod_geoip.c:16:
vmod_geoip.c: In function 'vmod_event':
vmod_geoip.c:27:20: error: 'VCL_EVENT_LOAD' undeclared (first use in this function)
   xxxassert(evt == VCL_EVENT_LOAD);
                    ^
/usr/include/varnish/vas.h:68:8: note: in definition of macro 'xxxassert'
  if (!(e)) {       \
        ^
vmod_geoip.c:27:20: note: each undeclared identifier is reported only once for each function it appears in
   xxxassert(evt == VCL_EVENT_LOAD);
                    ^
/usr/include/varnish/vas.h:68:8: note: in definition of macro 'xxxassert'
  if (!(e)) {       \
        ^
vmod_geoip.c:21:60: error: unused parameter 'evt' [-Werror=unused-parameter]
 vmod_event(VRT_CTX, struct vmod_priv *pp, enum vcl_event_e evt)

Please help me check error. Thank very much.

**Comment by fgsch** [comment]
Which branch are you using?
For Varnish 4 you need to use the 4.0 branch.

**Comment by nnhiep** [comment]
Thank Federico G. Schwindt

I have successfully installed the 4.0 branch.

**Comment by fgsch** [comment]
You are welcome. I will close this now.
