### ISSUE TITLE
make check failing

### ISSUE THREAD

**Issue by alexwybraniec** [varnish/libvmod-geoip#9]
On my Ubuntu 14.04 server, which is fully up to date, make check Test 1 fails.

https://gist.github.com/alexwybraniec/c22b4e828a5bed8a6585377fad1f9130

Result:
***  v1    1.4 debug| "Assert error in vmod_country_code(), vmod_geoip.c line 71:\n
***  v1    1.4 debug|   Condition((pp->priv) != 0) not true.\n

Any idea what I'm doing wrong? 

If I enable the vmod in the varnish, calling geoip.country_code result in blank pages.

We previously had a working version of the vmod, but that broke following an "apt-get upgrade"

Any help appreciated.

Alex W

**Comment by dridi** [comment]
I tried on an up-to-date Trusty with both varnish 4.1.5 and 4.1.6 (released after you reported this issue) and couldn't reproduce your failure. Which version of the VMOD are you running? I tried the master branch and the latest tag.

**Comment by dridi** [comment]
ETIMEDOUT

**Comment by dridi** [comment]
Well well well, if it isn't my good old friend irony...

https://travis-ci.org/varnish/libvmod-geoip/jobs/350318426

**Comment by rezan** [comment]
Fixed https://github.com/varnish/libvmod-geoip/commit/9cc5c4ef0c81394beae414189871effe83481c3d
